# Generated by Django 4.1.5 on 2023-02-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_question_answer_question_negativemarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='postivemarks',
            new_name='positivemarks',
        ),
    ]
