# Generated by Django 4.1.5 on 2023-02-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_rename_postivemarks_question_positivemarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_response',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
